### ISSUE TITLE
it says result_dict not defined in post_processing.py

### ISSUE THREAD

**Issue by WhoSJackie** [JJBOY/BMN-Boundary-Matching-Network#30]
it says result_dict not defined in post_processing.py,NameError: name 'result_dict' is not defined
how to solve it

**Comment by JJBOY** [comment]
I dont miss this problem ， it perhaps due to different python version or OS.  My python version=3.6 and run on Ubuntu.  Actually， I defined the result_dict in post_processing.py：

https://github.com/JJBOY/BMN-Boundary-Matching-Network/blob/45d05146822b85ca672b65f3d030509583d0135a/post_processing.py#L105

**Comment by WhoSJackie** [comment]
yes and i run it on windows10 .let me try some solution thx however
